var matrix1 = {"Title":"matrix1","Year":"1999","Rated":"R","Released":"31 Mar 1999","Runtime":"136 min","Genre":"Action, Sci-Fi","Director":"Andy Wachowski, Lana Wachowski","Writer":"Andy Wachowski, Lana Wachowski","Actors":"Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving","Plot":"A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.","Language":"English","Country":"USA, Australia","Awards":"Won 4 Oscars. Another 33 wins & 40 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTkxNDYxOTA4M15BMl5BanBnXkFtZTgwNTk0NzQxMTE@._V1_SX300.jpg","Metascore":"73","imdbRating":"8.7","imdbVotes":"1,119,993","imdbID":"tt0133093","Type":"movie","Response":"True", "Oscars": ["Best Film Editing","Best Sound","Best Effects, Sound Effects Editing","Best Effects, Visual Effects"], "Trailer":"https://www.youtube.com/embed/_Ls19O-9p3s"}


var matrix2 = {"Title":"matrix2","Year":"2003","Rated":"R","Released":"15 May 2003","Runtime":"138 min","Genre":"Action, Sci-Fi","Director":"Andy Wachowski, Lana Wachowski","Writer":"Andy Wachowski, Lana Wachowski, Andy Wachowski (characters), Lana Wachowski (characters)","Actors":"Ray Anthony, Christine Anu, Andy Arness, Alima Ashton-Sheibu","Plot":"Neo and the rebel leaders estimate that they have 72 hours until 250,000 probes discover Zion and destroy it and its inhabitants. During this, Neo must decide how he can save Trinity from a dark fate in his dreams.","Language":"English, French","Country":"USA, Australia","Awards":"5 wins & 21 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjA0NDM5MDY2OF5BMl5BanBnXkFtZTcwNzg5OTEzMw@@._V1_SX300.jpg","Metascore":"62","imdbRating":"7.2","imdbVotes":"400,966","imdbID":"tt0234215","Type":"movie","Response":"True","Oscars": ["Best Science Fiction Film(Nominated)","Best Costumes(Nominated)"],"Trailer":"https://www.youtube.com/embed/kYzz0FSgpSU"}
	
var matrix3 = {"Title":"matrix3","Year":"2003","Rated":"R","Released":"05 Nov 2003","Runtime":"129 min","Genre":"Action, Sci-Fi","Director":"Andy Wachowski, Lana Wachowski","Writer":"Andy Wachowski, Lana Wachowski, Andy Wachowski (characters), Lana Wachowski (characters)","Actors":"Mary Alice, Tanveer K. Atwal, Helmut Bakaitis, Kate Beahan","Plot":"The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.","Language":"English, French","Country":"Australia, USA","Awards":"1 win & 19 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTkyNjc4NTQzOV5BMl5BanBnXkFtZTcwNDYzMTQyMQ@@._V1_SX300.jpg","Metascore":"47","imdbRating":"6.7","imdbVotes":"346,296","imdbID":"tt0242653","Type":"movie","Response":"True","Oscars": ["NO AWARDS(piece of crap)"],"Trailer":"https://www.youtube.com/embed/hMbexEPAOQI"}	

var matrixArr = [matrix1,matrix2,matrix3]

export { matrixArr }